### ISSUE TITLE
Support for Scala 2.12

### ISSUE THREAD

**Issue by DanielaSfregola** [underscoreio/slickless#12]
Could you please release a version for Scala 2.12?

Thanks!
Daniela

**Comment by DanielaSfregola** [comment]
Please, have a look at PR https://github.com/underscoreio/slickless/pull/13.

This is blocking us from upgrading to Scala 2.12, so it would be great if this could be merged and released as soon as possible.

**Comment by d6y** [comment]
Thank you @DanielaSfregola - that's now on its way to Sonatype. Give it a couple of hours and hopefully it'll be avalable.
