### ISSUE TITLE
table with 144 columns inevitably causes a stackoverflowerror when compiling

### ISSUE THREAD

**Issue by normana400** [underscoreio/slickless#22]
I've isolated the cause of my stackoverflow error to the def * method that chains all 144 columns using the slickless "::" class. 

aka: 

 `  def * = ( col1 :: col2 :: col3 ::
....  col143 :: col144 :: HNil).mappedWith(Generic[MyCaseClass])`

There should be an alternative way to constuct the * def that doesn't involve the mass recursion?  After all this is the "BigData" solution to the 22 constructor limit in scala case classes / tuples.

**Comment by d6y** [comment]
Thanks for the report.

**Comment by d6y** [comment]
@normana400 Have you tried to increase the stack size? E.g., `sbt -J-Xss4M`

**Comment by normana400** [comment]
I was hoping for a solution that didn't involve me having to custom tweak every present or future server / ide that needs to compile, build, or develop my team's project

**Comment by d6y** [comment]
Sure - so a couple of options:

1. You can probably configure `-Xss` in your SBT build for everywhere that compiles the code.

or

2. Use Slick's built-in HList with the built-in  Slick`mapTo[T]` macro which _may_ not need the `-Xss` setting (although it may do if the Scala compiler has difficulty compiling a case class of that size with the default stack size setting).

Hope that helps.
