### ISSUE TITLE
Alternative to tails?

### ISSUE THREAD

**Issue by alexanderzafirov** [underscoreio/slickless#3]
Hello,

I recently ran in the tuple problem of Slick and stumbled across this neat library. I made it work with my 53 columns - all good. My question is - is there a better way to access a specific column in the class other this?

```
val id = ltm.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail
            .tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail
            .tail.tail.tail.head
```

It seems kind of ridiculous :D

I know I'm constructing a list but it takes me quite a while to pinpoint my column just by the type.

**Comment by d6y** [comment]
Hi @alexanderzafirov 

Do you mean something like this:

``` scala
scala> import shapeless._
import shapeless._

scala> val h = "A" :: "B" :: "C" :: HNil
h: shapeless.::[String,shapeless.::[String,shapeless.::[String,shapeless.HNil]]] = A :: B :: C :: HNil

scala> h(0)
res1: String = A

scala> h(1)
res2: String = B

scala> h(2)
res3: String = C

scala> h(3)
<console>:23: error: Implicit not found: shapeless.Ops.At[shapeless.::[String,shapeless.::[String,shapeless.::[String,shapeless.HNil]]], nat_$macro$5.N]. You requested to access an element at the position nat_$macro$5.N, but the HList shapeless.::[String,shapeless.::[String,shapeless.::[String,shapeless.HNil]]] is too short.
       h(3)
```

?

**Comment by alexanderzafirov** [comment]
Looks good but when I try to use it I get a result of type __at.Out__ since the apply method goes like this:
```
def apply[N <: Nat](implicit at : At[L, N]) : at.Out = at(l)
```
I tried specifying the type of the result I want like ```ltm.apply[DateTime](19)``` but I get some compile error. If you don't want to bother with this one you can close the issue. I think that I should be good from here on. Thanks for quick response :+1:

**Comment by d6y** [comment]
I can't see an obvious problem. If you want to put together a sample GitHub project for us to look at, happy to do that.
