### ISSUE TITLE
"No matching Shape found" error introduced in 0.3.3

### ISSUE THREAD

**Issue by nivekastoreth** [underscoreio/slickless#42]
I was recently upgrading our dependencies, and ran across the following issue when attempting to migrate past slickless 0.3.2:

```
[error] C:\build\public\slickless\src\test\scala\slickless\NestedSpec.scala:22:73: No matching Shape found.
[error] Slick does not know how to map the given types.
[error] Possible causes: T in Table[T] does not match your * projection,
[error]  you use an unsupported type in a Query (e.g. scala List),
[error]  or you forgot to import a driver api into scope.
[error]   Required level: L
[error]      Source type: slick.lifted.Rep[Long] :: slick.lifted.MappedProjection[NestedSpec.this.Department,(Long, String)] :: slick.lifted.MappedProjection[NestedSpec.this.Department,(Long, String)] :: slick.lifted.Rep[String] :: shapeless.HNil
[error]    Unpacked type: this.Repr
[error]      Packed type: P
[error]     def * = (id :: department :: department :: email :: HNil).mappedWith(Generic[Employee])
[error]                                                                         ^
[error] one error found
```

While it is not exactly a real-world scenario, you can replicate the issue by making the following changes on the latest `master` branch (8e324eed016ebe68b29da7dda8008020cf6e9766):
```
jmaki@jmaki-pc /build/public/slickless
$ git diff
diff --git a/src/test/scala/slickless/NestedSpec.scala b/src/test/scala/slickless/NestedSpec.scala
index 5e750b9..6b45ad5 100644
--- a/src/test/scala/slickless/NestedSpec.scala
+++ b/src/test/scala/slickless/NestedSpec.scala
@@ -9,7 +9,7 @@ class NestedSpec extends Spec {

   case class Department(id: Long, city: String)

-  case class Employee(id: Long, dept: Department, email: String)
+  case class Employee(id: Long, dept1: Department, dept2: Department, email: String)

   class Employees(tag: Tag) extends Table[Employee](tag, "emps") {
     def id             = column[Long]("id", O.PrimaryKey, O.AutoInc)
@@ -19,7 +19,7 @@ class NestedSpec extends Spec {

     def department = (departmentId, departmentCity).mapTo[Department]

-    def * = (id :: department :: email :: HNil).mappedWith(Generic[Employee])
+    def * = (id :: department :: department :: email :: HNil).mappedWith(Generic[Employee])
   }

   lazy val emps = TableQuery[Employees]
@@ -28,7 +28,7 @@ class NestedSpec extends Spec {
     "should support inserts and selects" in {
       val db = Database.forConfig("h2")

-      val emp = Employee(1L, Department(42L, "Brighton"), "dave@example.org")
+      val emp = Employee(1L, Department(42L, "Brighton"), Department(42L, "Brighton"), "dave@example.org")

       val action = for {
         _   <- emps.schema.create

```

If feasible, it's technically possible to work around this by using `mapTo` instead of `mappedWith` but this approach does not work well when using case classes with custom companion objects since you likely have to define `tupled` inside these companion objects.

**Comment by d6y** [comment]
Thanks for the report @nivekastoreth
 
Can I confirm with you: that code used to compile with Slickless 0.3.2, Slick 3.2.0, with Scala 2.12?

**Comment by nivekastoreth** [comment]
Those are the versions we were on that compiled. Moving past those introduced the bug (I believe via https://github.com/underscoreio/slickless/commit/7706def2b869631a06180a06a3907b870251b12c)

**Comment by d6y** [comment]
@nivekastoreth there's a `0.3.6-SNAPSHOT` on its way to Sonatype if you want to try that. It's for Scala 2.11, 2.12, and 2.13.

**Comment by nivekastoreth** [comment]
Awesome, thanks.  I'll give it a go on Monday, but looking at the commit, your change makes sense and as long as that unit test passes I'm fairly sure that fixes me.

To be fair to the original implementation, I didn't notice the issue even though I knew it was there and had been looking for it for... quite a while.  Thanks a bunch

**Comment by nivekastoreth** [comment]
Just tried on the project I originally ran into this on, and everything compiles as it should!
